# Generated by Django 5.1.5 on 2025-01-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_tags_delete_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="posts/images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="hero_image",
            field=models.ImageField(upload_to="posts/hero_images/"),
        ),
    ]
