name: Deploy to Server

on:
  push:
    branches: [ "prod" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Blog Docker image
      run: docker compose up -d
    - name: Run tests
      run: docker exec blog sh -c "pytest ."

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build  # This ensures 'deploy' runs only if 'build' succeeds
    if: success()  # Additional check to ensure the previous job succeeded
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Project
        id: build  # Assign an ID to the build step
        run: |
          echo "Building project..."
          # Add your build commands here
          echo "Build completed."

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            sudo docker compose -f docker-compose-prod.yml stop
            git pull origin prod
            sudo docker compose -f docker-compose-prod.yml restart