name: Todoapp Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Blog Docker image
      run: docker compose up -d
    - name: Run tests
      run: docker exec todoapp sh -c "pytest ."
